### ISSUE TITLE
Using pyigtl to pass in camera image into 3D slicer

### ISSUE THREAD

**Issue by pj-rit** [lassoan/pyigtl#1]
Hello, 
This is more of a question than an issue. I'm trying to incorporate a 3rd party camera (IDS uEye) into 3d slicer. However, I'm not a c++ or any sort of software developer so the instructions to add a device to PLUS toolkit are a bit daunting. I found this utility and was wondering if I can pass in a Vector image (aka RGB) though the OpenIGTLink. I was able to pass in the image as a scalar. 

As a side not, The other method I thought of trying was creating a module which would call the python API directly, but I'm not sure how I would structure that to create another thread to run in the background. 
Thanks for any help!

**Comment by lassoan** [comment]
Yes, you can send an RGB image using pyigtl (as a 4D image).

**Comment by pj-rit** [comment]
Thanks, 
I tried to send in the image as a [h,w,3,1] and as a [3,h,w,1] which doesn't work, so I guess I don't understand what you mean by making it a 4D image.

**Comment by lassoan** [comment]
Color image sending works well. For example:

```
# Generate image (colored circle)
import numpy as np
image_size = [500, 300]
radius = 60
color = [250, 50, 150]
cx = 2 * radius
cy = 3 * radius
y, x = np.ogrid[-cx:image_size[0]-cx, -cy:image_size[1]-cy]
mask = x*x + y*y <= radius*radius
# Shape: component, i, j, k
voxels = np.ones((3, image_size[0], image_size[1], 1))
voxels[0, mask] = color[0]
voxels[1, mask] = color[1]
voxels[2, mask] = color[2]
# numpy image axes are in kjic order, while we generated the image with cijk axes
voxels = np.transpose(voxels, axes=(3, 2, 1, 0))

# Send image
import pyigtl
server = pyigtl.OpenIGTLinkServer(port=18944)
#while not server.is_connected():
#    # Wait for client to connect
#    sleep(0.1)
image_message = pyigtl.ImageMessage(voxels, device_name="Image")
server.send_message(image_message, wait=True)
server.server_close()
```

**Comment by pj-rit** [comment]
Thank You! I'm not sure why I missed that example code.  I figured out what I was doing wrong. I needed to delete the image  node in Slicer as it was being created as a scalar node
